name: Jaaw

options:
  bundleIdPrefix: com.boredlol

targets:
  Jaaw:
    type: application
    platform: iOS
    deploymentTarget: "26.0"

    sources:
      - Jaaw

    info:
      path: Jaaw/Info.plist
      properties:
        CFBundleDisplayName: "JAAW"
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.boredlol.jaaw
        SWIFT_VERSION: "5.0"